source 'https://rubygems.org'

gem 'cpf_cnpj'
gem 'json'
gem 'nokogiri'
gem 'os'
gem 'rest-client'

#Todas gems colocadas abaixo será instalada ao ser executado "bundle"

#Este arquivo é responsável por conter todas dependências de gems
#Apenas com o comando "bundle" dentro deste diretório, será instalada todas dependências desse projeto